### ISSUE TITLE
Sanitizer test failure doesn't fail CI

### ISSUE THREAD

**Issue by jpeletier** [SanderMertens/flecs#1404] opened 2024-10-17 12:48 UTC
**Describe the bug**
The following test `Basic.entity_iteration_w_match_empty_tables` does not pass with sanitizer on since commit `4591db1ddda42014307e6fe8dcb43ee0e391cddc`

However, it seems query tests are not being run with `--sanitize`  in CI, because this has gone unnoticed.

```
fatal: block_allocator.c: 94: assert: ba->alloc_count == 0 (size = 3152) (LEAK_DETECTED)
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(flecs_dump_backtrace+0xcc) [0x7f16fdbd380d]
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(+0x7d4c70) [0x7f16fdbd4c70]
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(ecs_printv_+0x342) [0x7f16fd9079fa]
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(ecs_log_+0x1c3) [0x7f16fd907fbe]
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(ecs_assert_log_+0x191) [0x7f16fd9094ce]
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(flecs_ballocator_fini+0x24c) [0x7f16fdb56ed4]
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(+0x76574d) [0x7f16fdb6574d]
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(ecs_set_stage_count+0x124f) [0x7f16fdb676ae]
/home/jm/bake/x64-Linux/sanitize/lib/libflecs.so(ecs_fini+0x1bed) [0x7f16fdcd390f]
bin/x64-Linux-sanitize/query(+0x6465c5) [0x5596ea81d5c5]
/home/jm/bake/lib/libbake_test.so(+0x2ed5) [0x7f16fe5f1ed5]
/home/jm/bake/lib/libbake_test.so(bake_test_run+0x3c4) [0x7f16fe5f3999]
bin/x64-Linux-sanitize/query(+0xb587d6) [0x5596ead2f7d6]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f16fc829d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f16fc829e40]
bin/x64-Linux-sanitize/query(+0x2f6265) [0x5596ea4cd265]
FAIL: Basic.entity_iteration_w_match_empty_tables aborted
To run/debug your test, do:
export $(bake env)
test/query/bin/x64-Linux-sanitize/query Basic.entity_iteration_w_match_empty_tables --param cache_kind=auto
```

**To Reproduce**
```
bake clean
bake run test/query --cfg sanitize
```

**Comment by SanderMertens** [comment] 2024-10-18 16:46
Hm that's odd, query tests are definitely ran with sanitizer: https://github.com/SanderMertens/flecs/actions/runs/11394483911/job/31704912299

Which platform is this?

**Comment by SanderMertens** [comment] 2024-10-18 22:46
It's not a bug in the code but an issue in the test case. Checked in a fix, but leaving the issue open for fixing the CI issue.

**Comment by SanderMertens** [comment] 2024-12-18 21:49
I've seen sanitizer builds fail since, seems like it was a temporary glitch.

**Closed by SanderMertens** 2024-12-18 21:49 UTC
Labels: ci
