### ISSUE TITLE
Module destructor gets called multiple times

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#426] opened 2021-05-29 19:30 UTC
**Describe the bug**
MModule destructor is called multiple times  in this code scenario:

```c
namespace Test {

static std::vector<system> Systems;

class MModule {
public:
    MModule(ecs &ECS) {
        ECS.module<MModule>();
        Systems.Add(ECS.system<>("Just a system", "").kind(0).iter([](iter &){}));
    }
    ~MModule() {
        Debugf("Destructing...");
    }
    
    
};
}

int main(){
    stdcpp_set_os_api();
    ecs *ECSPtr = new ecs;
    ecs &ECS = *ECSPtr;
    ECS.set_threads(8);
    
    if (true) {
        ECS.import<Test::MModule>();
        delete ECSPtr;
    }
}
```

**Expected behavior**
Module destructor should be called just once

**Comment by SanderMertens** [comment] 2021-06-07 01:03
This code doesn't compile, I think I have your behavior reproduced with this code:
```c
class MModule {
public:
    MModule(flecs::world &ecs) {
        ecs.module<MModule>();
        ecs.system<>("Just a system", "").kind(0).iter([](flecs::iter &){

		});
    }
    ~MModule() {
        printf("Destructing...\n");
    }
};

int main(){
	flecs::world ecs;
	ecs.import<MModule>();
}
```

**Comment by SanderMertens** [comment] 2021-06-07 01:36
The issue is a fun one. What happens here is that when the system is added to the module, `(ChildOf, MModule)` is added to the system entity. Because `ChildOf` is a tag, and `MModule` is not, the relation type defaults to `MModule`.

This means that both the system and module have an instance of the `MModule` component, which both are destructed when the world is cleaned up.

To solve this a feature is needed that I've been wanting to add for a while, which is a way to define that no matter what the object of a relation is, it'll never be interpreted as a component. Should be a relatively small thing to add.

A similar thing would happen if you were to do something like this:
```c
auto c = world.component<Position>();
auto e = ecs.entity().child_of(c); // (ChildOf, Position) is added with Position data
```

**Comment by SanderMertens** [comment] 2021-06-07 17:23
Fixed it by adding a `Tag` property that can be added to an entity to indicate that if the entity is used as a relation in a pair, it will never be associated with any data even if one of the pairs is a component: https://github.com/SanderMertens/flecs/blob/master/docs/Relations.md#tag-relations

**Comment by SanderMertens** [comment] 2021-06-07 17:27
This change is a breaking change for the following reasons:
- if an application used something like `ChildOf, Position` before, `Position` data will no longer be added
- a name resolving issue was fixed. This causes some query expressions that use incorrect identifiers to resolve builtin components to no longer work. For example, `EcsName`, `EcsPrefab` longer work. Instead, `Name` or `flecs.core.Name` should be used.

**Closed** 2021-06-07 17:28 UTC
Labels: breaking change, bug

**Comment by Hexlord** [comment] 2021-06-08 18:49
Nice! Thank you
