### ISSUE TITLE
Allow for atfini logic to be defined inside module destructor

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#405] opened 2021-05-16 05:33 UTC
**Describe the problem you are trying to solve.**
Some modules obtain Engine-level resources that need to be explicitly cleaned up on flecs world destruction. To do this, we resort to `ecs_atfini` C api.

**Describe the solution you'd like**
It would be neat to be able to define that cleanup logic at module destructor.
struct MModule{
 MModule();
 ~MModule(); // <- Cleanup here.
}

**Comment by SanderMertens** [comment] 2021-05-16 05:42
Duplicate of #396

**Closed by SanderMertens** 2021-05-16 05:42 UTC
Labels: enhancement
