### ISSUE TITLE
ecs_snapshot_take && ecs_snapshot_restore

### ISSUE THREAD

**Issue by hbiblia** [SanderMertens/flecs#301] opened 2021-01-19 20:53 UTC
**Describe the bug**

When I run "_ecs_load_world_file ()" the first time it works, it loads everything instead, but if I run it again it explodes and shows this error:  **`err : assert(!elem_size || elem_size == map->type_elem_size) ../source/libs/flecs/flecs.c:17341: invalid parameters`**

```
void _ecs_save_world_file(void)
{
    FILE *file = fopen("test.sav", "wb");
    ecs_snapshot_t *s = ecs_snapshot_take(world);
    fwrite(&s, sizeof(ecs_snapshot_t*), 1, file);
    fclose(file);
}
```
```
void _ecs_load_world_file(void)
{
    FILE *file = fopen("test.sav", "r");
    ecs_snapshot_t *s = NULL;
    fread(&s, sizeof(ecs_snapshot_t*), 1, file);
    ecs_snapshot_restore(world, s);
    fclose(file);
}
```

Upon further testing this explodes:

```
  ecs_snapshot_t *s = ecs_snapshot_take(world);
  ecs_snapshot_restore(world, s);
  ecs_snapshot_restore(world, s);
```

**Comment by SanderMertens** [comment] 2021-01-20 17:19
Ah, this doesn't work. You cannot write a snapshot to a file. If you want to save the world to a file, see the save_to_file example: https://github.com/SanderMertens/flecs/tree/master/examples/c/31_save_to_file

Additionally, `ecs_snapshot_restore` is a destructive function. You cannot restore the same snapshot twice, as the data inside the snapshot is moved (not copied) to the world. If you need to save the snapshot after restoring, you can take another snapshot right after restoring.

Closing this issue as this is not a bug, but feel free to open another one if you have more questions!

**Closed by SanderMertens** 2021-01-20 17:19 UTC
Labels: bug

**Comment by hbiblia** [comment] 2021-01-20 20:07
Hi aaah I see, I tried https://github.com/SanderMertens/flecs/tree/master/examples/c/31_save_to_file but it doesn't seem to work the same way. Thank you!!
