### ISSUE TITLE
Specific query in explorer triggers assert in attached app

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#655] opened 2022-02-23 19:45 UTC
**Describe the bug**
entering the query `ChildOf(52, _Y)` into a flecs explorer which is attached to the app triggers an assert
`ecs_check(ecs_is_valid(rule->world, op->subject),  ECS_INVALID_PARAMETER, NULL);`
Might actually be an exception coming from inside the assert, I don't actually see the assert error message in the output, just this:
`Exception: Exception 0x80000003 encountered at address 0x7ffe9f847475`

**To Reproduce**
 `ChildOf(52, _Y)` into a flecs explorer while attached to an application 

```
reg_get_table(const ecs_rule_t *,ecs_rule_op_t *,ecs_rule_reg_t *,int) flecs.c:17589
eval_store(ecs_iter_t *,ecs_rule_op_t *,int,bool) flecs.c:20788
eval_op(ecs_iter_t *,ecs_rule_op_t *,int,bool) flecs.c:20950
ecs_rule_next_instanced(ecs_iter_t *) flecs.c:21243
ecs_rule_next(ecs_iter_t *) flecs.c:21172
ecs_iter_to_json_buf(const ecs_world_t *,ecs_iter_t *,ecs_strbuf_t *,const ecs_iter_to_json_desc_t *) flecs.c:27325
rest_reply(const ecs_http_request_t *,ecs_http_reply_t *,void *) flecs.c:27968
handle_request(ecs_http_server_t *,ecs_http_request_impl_t *) flecs.c:28993
dequeue_requests(ecs_http_server_t *,float) flecs.c:29017
ecs_http_server_dequeue(ecs_http_server_t *,float) flecs.c:29172
DequeueRest(ecs_iter_t *) flecs.c:28037
ecs_run_intern(ecs_world_t *,ecs_stage_t *,unsigned long long,EcsSystem *,int,int,float,int,int,void *) flecs.c:25674
ecs_run_pipeline(ecs_world_t *,unsigned long long,float) flecs.c:14185
ecs_workers_progress(ecs_world_t *,unsigned long long,float) flecs.c:13557
ecs_run_pipeline(ecs_world_t *,unsigned long long,float) flecs.c:14141
ecs_progress(ecs_world_t *,float) flecs.c:14374
```

**Comment by SanderMertens** [comment] 2022-02-23 21:20
Checked in a fix. The cause of the error was that id `52` was not alive. The reason the error wasn't logged to the console was because the REST API was capturing it.

Trying to create a query with a not alive id will now throw an error.

**Closed by SanderMertens** 2022-02-23 21:20 UTC
Labels: bug
