### ISSUE TITLE
Cached module import not working properly

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#591] opened 2022-01-05 17:20 UTC
**Describe the bug**
Code below asserts like shown in [discord](https://discord.com/channels/633826290415435777/689025747909607434/928335218899816458) 

```c
struct Module1{
    Module1(ecs &ECS) {
        ECS.module<Module1>();
    }
};
struct Module2{
    Module2(ecs &ECS) {
        ECS.module<Module2>();
    }
};
struct Module3{
    Module3(ecs &ECS) {
        ECS.module<Module3>();
    }
};

{
    flecs::world World;
    World.import<Module1>();
    World.import<Module3>();
}
{
    flecs::world World;
    World.import<Module1>();
    World.import<Module2>();
    World.import<Module3>(); // this asserts
}
```

**Expected behavior**
No assert happens

**Comment by SanderMertens** [comment] 2022-01-05 17:37
This is expected behavior. What happens is along the lines of:
World 1:
- Module1 is registered with id 10
- Module3 is registered with id 11

World 2:
- Module1 is registered with id 10
- Module2 is registered with id 11
- Module3 is registered with existing id 11 << error >>

The issue is that the 2nd world can't know of `Module3` before it is registered, which means it can issue the id for the module to something else. This is why when using overlapping components/modules between multiple worlds, you always need to preregister components/modules at least once.

The only way I can think to address this would be to use some kind of hashed id for the component/module ids, but that's not how flecs works (they're sequential component ids).

Closing this issue, as this is expected behavior.

**Closed by SanderMertens** 2022-01-05 17:37 UTC
