### ISSUE TITLE
Accessing parent entity during triggers leads to unexpected results.

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#480] opened 2021-09-08 09:14 UTC
**Describe the bug**
In my code base, adding a custom relation to an entity leads to a crash reported here with 1 screenshot ( https://discord.com/channels/633826290415435777/689025747909607434/884915189735129100 ) 
A more simple reproduce of ChildOf corruption that does not crash, but yields incorrect program state is listed below, it does not even involve custom relation.

**To Reproduce**
```c
struct MyStruct {
    int Field;
};
void SanityTest(flecs::world &ECS) {    
    ECS.trigger<const MyStruct>().event(flecs::OnRemove).iter([&](iter &Iter){
        for(auto Index : Iter) {
            auto Entity = Iter.entity(Index);
            auto Parent = Entity.get_object(flecs::ChildOf);
            printf("Destroying %s son of %s", Entity.name().c_str(), Parent ? Parent.name().c_str() : "<noone>");
        }
    });
    
    auto Entity = ECS.entity("Entity").add<MyStruct>();
    auto OtherEntity = ECS.entity("OtherEntity");
    ECS.scope(Entity, [&]() {
        auto Child2 = ECS.entity("Child2").add<MyStruct>();
        auto InnerChild = ECS.entity("InnerChild").child_of(Child2).add<MyStruct>();
    });
    
    
    Entity.destruct();
    OtherEntity.destruct();
}
```

**Expected behavior**
Destroying InnerChild son of **Child2**
Destroying Child2 son of Entity
Destroying Entity son of <noone>

**Actual behavior**
Destroying InnerChild son of **Entity**
Destroying Child2 son of Entity
Destroying Entity son of <noone>

**Additional context**
It repros with both OnAdd and OnRemove, but replacing `.child_of` with `.scope` prevents the repro from occurring.
My idea is that it has something to do with table transitions when custom relations are involved, but I can't really explain the difference between `.child_of` and `.scope` in that case, maybe state is already corrupted before even creating the InnerChild.

**Comment by SanderMertens** [comment] 2021-09-08 09:28
I'll have to look into this but what I _think_ is happening here is that the `OnRemove` handler is accessing a component from a parent (`Child2`) which just has been deleted itself. Because the delete operation is still in progress the storage is still "in flux" and as a result the data for the parent looks corrupted.

My guess is that if you print the entity ids vs. the entity names, you should actually see that they are correct.

This is a tricky problem (invoking callbacks in an operation that involves more than one entity/component, while ensuring that for each callback the storage is in a consistent state). I'll check back in when I know more.

**Comment by SanderMertens** [comment] 2021-09-08 09:29
Btw, I don't expect that the custom relationship affects this scenario much. Does the issue still reproduce when you remove this line?
```c
Child2.add(Relation, OtherEntity);
```

**Comment by Hexlord** [comment] 2021-09-08 09:59
> I'll have to look into this but what I _think_ is happening here is that the `OnRemove` handler is accessing a component from a parent (`Child2`) which just has been deleted itself. Because the delete operation is still in progress the storage is still "in flux" and as a result the data for the parent looks corrupted.

But it also applies to OnAdd, and even in case of removal, children should be removed first, right?

**Comment by Hexlord** [comment] 2021-09-08 20:31
Relation does not matter in the example, accessing parents from triggers is not allowed as per design, closing.

**Comment by Hexlord** [comment] 2021-09-16 20:14
Updated description and name, as the issue does indeed exist.

**Comment by SanderMertens** [comment] 2021-09-18 21:39
Dumb I didn't see this before, there is an issue in your code! You're using `child_of` inside the `scope` lambda which causes the entity to have 2 `ChildOf` relations. When I modify the code to this

```c
ECS.scope(Entity, [&]() {
   auto Child2 = ECS.entity("Child2").add<MyStruct>();

   ECS.scope(Child2, [&]() {
     auto InnerChild = ECS.entity("InnerChild").add<MyStruct>();
   });
});
```

The output is as expected:

```c
Destroying InnerChild son of Child2
Destroying Child2 son of Entity
Destroying Entity son of <noone>
```

**Comment by SanderMertens** [comment] 2021-09-18 21:44
Note that the original output is correct for the provided code. `get_object(flecs::ChildOf)` just happens to return the first parent. You can have it return the 2nd parent with `get_object(flecs::ChildOf, 1)`.

Having an entity with multiple `ChildOf` relations can lead to unexpected behavior and is usually not what you want. I'll eventually add a feature that lets you specify that a relation can only have one instance, in which case this code would have triggered an error.

Since the reported behavior is as expected, I'll close the issue.

**Closed by SanderMertens** 2021-09-18 21:44 UTC
Labels: bug

**Comment by Hexlord** [comment] 2021-09-19 11:20
> Note that the original output is correct for the provided code. `get_object(flecs::ChildOf)` just happens to return the first parent. You can have it return the 2nd parent with `get_object(flecs::ChildOf, 1)`.
> 
> Having an entity with multiple `ChildOf` relations can lead to unexpected behavior and is usually not what you want. I'll eventually add a feature that lets you specify that a relation can only have one instance, in which case this code would have triggered an error.
> 
> Since the reported behavior is as expected, I'll close the issue.

Hey, I even wrote it in original post :D
True, it is correct, good thing I removed all child_of-s from my code and now safe from such mistake.
```
Additional context
It repros with both OnAdd and OnRemove, but replacing .child_of with .scope prevents the repro from occurring.
```
