### ISSUE TITLE
Manual Systems - Matched Entities Received

### ISSUE THREAD

**Issue by teksoc-1** [SanderMertens/flecs#79] opened 2019-10-09 16:34 UTC
@SanderMertens It appears for manual systems, the entire collection of matched entities is not received at once, but rather the respective manual system is invoked iteratively per each matched entity. Is this by design?

**Comment by SanderMertens** [comment] 2019-10-11 16:34
@teksoc-1 Can you post the code that reproduces this? A manual system should definitely return all matching entities _per archetype_, so this doesn't sound right.

**Comment by teksoc-1** [comment] 2019-11-01 13:53
@SanderMertens - sorry on the delay on this, will have to cycle back to this one, but just came across some thing else that will post in another issue wrt parent child hierarchy API usage/surprises, with sample code to support

**Comment by forsakenyang** [comment] 2020-04-13 10:58
I have meet this issue today. Here is a test case to reproduce.
```
struct Foo
{
    int foo;
};

struct Bar
{
    int bar;
};

void Simple_manual() {
    auto world = flecs::world();

    flecs::component<Foo>(world, "Foo");
    flecs::component<Bar>(world, "Bar");
    flecs::system<>(world, "TriggerOnSet")
        .signature("Foo, ?Bar")
        .kind(flecs::OnSet)
        .action([&world](flecs::rows &rows) {
            auto bars = rows.column<Bar>(2);
            if (bars.is_set())
                return;
            flecs::entity(world)
                .set<Bar>({.bar = 1})
                .set<Foo>({.foo = 1});
        });

    int counter = 0;
    auto ManualRun = flecs::system<>(world, "ManualRun")
                         .signature("Foo")
                         .kind(flecs::Manual)
                         .action([&counter](flecs::rows &rows) {
                             counter++;
                         });

    flecs::entity(world)
        .set<Foo>({.foo = 1});

    ecs_run(world.c_ptr(), ManualRun.id(), 0, nullptr);
    test_int(counter, 1);
}
```

FAIL: Simple.manual:87: counter (2) != 1

**Comment by forsakenyang** [comment] 2020-04-15 03:22
@SanderMertens I don't know wether creating new entity in OnSet system is a good practice. But it is a really weired behaviour that trigger manual system action multiple times by calling ecs_run once.

**Comment by SanderMertens** [comment] 2020-06-20 04:48
@forsakenyang @teksoc-1 Necromancing this issue and closing it, because:

- manual systems are no longer an explicit thing in v2 and now behave exactly like normal systems.

- v2 is about to get merged, and it significantly changes the behavior of what happens if you create entities inside OnSet systems. Operations such as add, remove and set are now _deferred_ and will be executed as soon as the OnSet system is executed.

@forsakenyang if you're still seeing this issue in v2 (keep an eye out on its release, it'll be soon), please let me know.

**Closed** 2020-06-20 04:55 UTC
