### ISSUE TITLE
Component arrays don't follow large type alignment (CPP)

### ISSUE THREAD

**Issue by nimble0** [SanderMertens/flecs#1471] opened 2024-12-13 01:14 UTC
**Describe the bug**
Components arrays for types with alignment of 64bytes+ are not aligned.

**To Reproduce**
Edited hello_world example:
```
#include <hello_world.h>
#include <iostream>
#include <type_traits>
#include <cstdint>

// Component types
struct alignas(256) Position {
	double x;
	double y;
};

template <typename T>
bool is_aligned(T* p)
{
	return reinterpret_cast<std::uintptr_t>(p) % std::alignment_of<T>::value == 0;
}

int main(int, char *[]) {
	// Create the world
	flecs::world ecs;

	auto e = ecs.entity()
		.set(Position{4, 4});

	std::cout << "Position alignment = " << std::alignment_of<Position>::value << "\n";

	ecs.query<Position>()
		.run([=](flecs::iter iter)
		{
			while(iter.next())
			{
				auto field = iter.field<Position>(0);
				std::cout << "Is aligned = " << is_aligned(&field[0]) << "\n";
			}
		});
}
```

**Expected behavior**
```
Position alignment = 256
Is aligned = 1
```

**Actual behavior**
```
Position alignment = 256
Is aligned = 0
```

**Additional context**
Compiler: gcc (GCC) 14.2.1 20240910

**Comment by SanderMertens** [comment] 2024-12-14 19:19
Duplicate of https://github.com/SanderMertens/flecs/issues/478

**Closed by SanderMertens** 2024-12-14 19:19 UTC
Labels: bug
